teljari_is=function(){var __p_w=window;var __p_d=__p_w.document;var __p_n=__p_w.navigator;var __p_l=__p_w.location;var __p_b=__p_d.body?__p_d.body:false;var __p_s=screen;var __p_da=new Date;var __p_ud="undefined";var __p_css;var __p_r_w="";var __p_r_h="";var __p_r_c="";var __p_r_k="";var __p_r_j;var __p_r_r="";var __p_r_t=__p_d.title;var __p_r_u;var __p_r_z=__p_da.getTimezoneOffset();var __p_r_s="";var __p_r_l="";var __p_r_lo=__p_l.href;var __p_r_f=0;var __p_r_v=0;var __p_r_sl=0;var __p_r_x=0;var __p_r_e=
__p_n.javaEnabled()?1:0;var __p_r_uid="";var __p_r_chsum;var __p_r_cv=2;var __p_n_ua=__p_n.userAgent;var __p_n_ua_l=__p_n_ua.toLowerCase();var __p_n_an=__p_n.appName;var __p_n_av=__p_n.appVersion;var __p_b_o;var __p_b_ie;var __p_b_ie5;var __p_b_ns;var __p_b_ns6;var __p_b_mac;var __p_x_o;var __p_b_v;var __p_msd="";var __p_l_pr;var __p_ol_r=false;var __p_ou_r=false;var __p_ob_r=false;var __p_of_r=false;var flashVer=-1;var totalTime=0;var timerEnd,timerStart,fullTimerStart;var javascriptVersion=function(){var agt=
navigator.userAgent.toLowerCase();var is_major=parseInt(navigator.appVersion);var is_minor=parseFloat(navigator.appVersion);var is_nav=agt.indexOf("mozilla")!=-1&&agt.indexOf("spoofer")==-1&&agt.indexOf("compatible")==-1&&agt.indexOf("opera")==-1&&agt.indexOf("webtv")==-1&&agt.indexOf("hotjava")==-1;var is_nav2=is_nav&&is_major==2;var is_nav3=is_nav&&is_major==3;var is_nav4=is_nav&&is_major==4;var is_nav4up=is_nav&&is_major>=4;var is_navonly=is_nav&&(agt.indexOf(";nav")!=-1||agt.indexOf("; nav")!=
-1);var is_nav6=is_nav&&is_major==5;var is_nav6up=is_nav&&is_major>=5;var is_gecko=agt.indexOf("gecko")!=-1;var is_ie=agt.indexOf("msie")!=-1&&agt.indexOf("opera")==-1;var is_ie3=is_ie&&is_major<4;var is_ie4=is_ie&&is_major==4&&agt.indexOf("msie 4")!=-1;var is_ie4up=is_ie&&is_major>=4;var is_ie5=is_ie&&is_major==4&&agt.indexOf("msie 5.0")!=-1;var is_ie5_5=is_ie&&is_major==4&&agt.indexOf("msie 5.5")!=-1;var is_ie5up=is_ie&&!is_ie3&&!is_ie4;var is_ie5_5up=is_ie&&!is_ie3&&!is_ie4&&!is_ie5;var is_ie6=
is_ie&&is_major==4&&agt.indexOf("msie 6.")!=-1;var is_ie6up=is_ie&&!is_ie3&&!is_ie4&&!is_ie5&&!is_ie5_5;var is_aol=agt.indexOf("aol")!=-1;var is_aol3=is_aol&&is_ie3;var is_aol4=is_aol&&is_ie4;var is_aol5=agt.indexOf("aol 5")!=-1;var is_aol6=agt.indexOf("aol 6")!=-1;var is_opera=agt.indexOf("opera")!=-1;var is_opera2=agt.indexOf("opera 2")!=-1||agt.indexOf("opera/2")!=-1;var is_opera3=agt.indexOf("opera 3")!=-1||agt.indexOf("opera/3")!=-1;var is_opera4=agt.indexOf("opera 4")!=-1||agt.indexOf("opera/4")!=
-1;var is_opera5=agt.indexOf("opera 5")!=-1||agt.indexOf("opera/5")!=-1;var is_opera5up=is_opera&&!is_opera2&&!is_opera3&&!is_opera4;var is_webtv=agt.indexOf("webtv")!=-1;var is_TVNavigator=agt.indexOf("navio")!=-1||agt.indexOf("navio_aoltv")!=-1;var is_AOLTV=is_TVNavigator;var is_hotjava=agt.indexOf("hotjava")!=-1;var is_hotjava3=is_hotjava&&is_major==3;var is_hotjava3up=is_hotjava&&is_major>=3;var is_js;if(is_nav2||is_ie3)is_js=1;else if(is_nav3)is_js=1.1;else if(is_opera5up)is_js=1.3;else if(is_opera)is_js=
1.1;else if(is_nav4&&is_minor<=4.05||is_ie4)is_js=1.2;else if(is_nav4&&is_minor>4.05||is_ie5)is_js=1.3;else if(is_hotjava3up)is_js=1.4;else if(is_nav6||is_gecko)is_js=1.5;else if(is_nav6up)is_js=1.5;else if(is_ie5up)is_js=1.3;else is_js=0;return is_js};var __p_e=function(v){return escape(v)};var __p_io=function(o,v){return o.indexOf(v)};var __p_zf=function(n){if(n<10)n="0"+n;return n};var __p_ss=function(s,l){return(s+"").substring(0,l)};var __p_fv=function(v){return typeof eval("__p_r_"+v)!=__p_ud?
eval("__p_r_"+v):""};var __p_pf=function(v){return parseFloat(v)};var __p_pi=function(v){return parseInt(v)};var __p_ms=function(){var a=arguments,r="";for(var i=0;i<a.length;i++)if(__p_e(__p_fv(a[i]))!="")r+=";"+a[i]+"="+__p_e(__p_fv(a[i]));return r};var ControlVersion=function(){var version;var axo;var e;try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");version=axo.GetVariable("$version")}catch(e){}if(!version)try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");version="WIN 6,0,21,0";
axo.AllowScriptAccess="always";version=axo.GetVariable("$version")}catch(e){}if(!version)try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version=axo.GetVariable("$version")}catch(e){}if(!version)try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version="WIN 3,0,18,0"}catch(e){}if(!version)try{axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");version="WIN 2,0,0,11"}catch(e){version=-1}return version};var getSilverlightVersion=function(){var SLVersion;try{try{var control=
new ActiveXObject("AgControl.AgControl");if(control.IsVersionSupported("3.0"))SLVersion=3;else if(control.IsVersionSupported("2.0"))SLVersion=2;else SLVersion=1;control=null}catch(e){var plugin=navigator.plugins["Silverlight Plug-In"];if(plugin)if(plugin.description==="1.0.30226.2")SLVersion=2;else SLVersion=parseInt(plugin.description[0]);else SLVersion=0}}catch(e){SLVersion=0}return SLVersion};var __p_ob=function(e){r=true;timerEnd=new Date;totalTime=totalTime+parseInt(timerEnd.getTime())-parseInt(timerStart.getTime());
if(__p_ob_r)r=__p_ob_r(e)};var __p_of=function(e){r=true;timerStart=new Date;if(__p_of_r)r=__p_of_r(e)};var doNothing=function(){};var __p_ou=function(e){r=true;timerEnd=new Date;totalTime=totalTime+parseInt(timerEnd.getTime())-parseInt(timerStart.getTime());fullTime=parseInt(timerEnd.getTime())-parseInt(fullTimerStart.getTime());__p_counthost_http="potency-cnt.teljari.is";__p_counthost_https="secure.teljari.is";if(__p_l_pr=="https")__p_counthost=__p_counthost_https;else __p_counthost=__p_counthost_http;
url=__p_l_pr+"://"+__p_counthost+"/potency/potency.php?o="+service_id+"&p="+page+"&i="+portion+"&pa="+Math.round(totalTime/1E3)+"&pf="+Math.round(fullTime/1E3);if(__p_d.images&&__p_d.images["__p_img"]&&__p_d.images["__p_img"].src!=url)if(__p_b_ie&&__p_css)__p_d.styleSheets[0].addImport(url);else{var __p_img=new Image;__p_img.src=url}if(__p_ou_r)r=__p_ou_r(e);return};var __p_ol=function(e){r=true;timerStart=new Date;fullTimerStart=new Date;if(__p_ol_r)r=__p_ol_r(e)};var __p_ie=function(){if(__p_r_j()>=
13)if(__p_w.addEventListener){__p_w.addEventListener("load",__p_ol,false);__p_w.addEventListener("blur",__p_ob,false);__p_w.addEventListener("focus",__p_of,false);__p_w.addEventListener("beforeunload",__p_ou,false)}else if(__p_w.attachEvent){__p_w.attachEvent("onload",__p_ol);__p_w.attachEvent("onblur",__p_ob);__p_w.attachEvent("onfocus",__p_of);__p_w.attachEvent("onunload",__p_ou)}};var __p_ccss=function(){if(__p_d.styleSheets&&__p_b_ie&&!__p_b_mac&&__p_b_ie5){__p_css=1;if(__p_d.styleSheets.length<
1)__p_d.write("<st"+'yle type="text/c'+'ss"></st'+"yle>");if(!__p_d.styleSheets[0]||!__p_d.styleSheets[0].addImport)__p_css=0}};var MD5=function(string){function RotateLeft(lValue,iShiftBits){return lValue<<iShiftBits|lValue>>>32-iShiftBits}function AddUnsigned(lX,lY){var lX4,lY4,lX8,lY8,lResult;lX8=lX&2147483648;lY8=lY&2147483648;lX4=lX&1073741824;lY4=lY&1073741824;lResult=(lX&1073741823)+(lY&1073741823);if(lX4&lY4)return lResult^2147483648^lX8^lY8;if(lX4|lY4)if(lResult&1073741824)return lResult^
3221225472^lX8^lY8;else return lResult^1073741824^lX8^lY8;else return lResult^lX8^lY8}function F(x,y,z){return x&y|~x&z}function G(x,y,z){return x&z|y&~z}function H(x,y,z){return x^y^z}function I(x,y,z){return y^(x|~z)}function FF(a,b,c,d,x,s,ac){a=AddUnsigned(a,AddUnsigned(AddUnsigned(F(b,c,d),x),ac));return AddUnsigned(RotateLeft(a,s),b)}function GG(a,b,c,d,x,s,ac){a=AddUnsigned(a,AddUnsigned(AddUnsigned(G(b,c,d),x),ac));return AddUnsigned(RotateLeft(a,s),b)}function HH(a,b,c,d,x,s,ac){a=AddUnsigned(a,
AddUnsigned(AddUnsigned(H(b,c,d),x),ac));return AddUnsigned(RotateLeft(a,s),b)}function II(a,b,c,d,x,s,ac){a=AddUnsigned(a,AddUnsigned(AddUnsigned(I(b,c,d),x),ac));return AddUnsigned(RotateLeft(a,s),b)}function ConvertToWordArray(string){var lWordCount;var lMessageLength=string.length;var lNumberOfWords_temp1=lMessageLength+8;var lNumberOfWords_temp2=(lNumberOfWords_temp1-lNumberOfWords_temp1%64)/64;var lNumberOfWords=(lNumberOfWords_temp2+1)*16;var lWordArray=Array(lNumberOfWords-1);var lBytePosition=
0;var lByteCount=0;while(lByteCount<lMessageLength){lWordCount=(lByteCount-lByteCount%4)/4;lBytePosition=lByteCount%4*8;lWordArray[lWordCount]=lWordArray[lWordCount]|string.charCodeAt(lByteCount)<<lBytePosition;lByteCount++}lWordCount=(lByteCount-lByteCount%4)/4;lBytePosition=lByteCount%4*8;lWordArray[lWordCount]=lWordArray[lWordCount]|128<<lBytePosition;lWordArray[lNumberOfWords-2]=lMessageLength<<3;lWordArray[lNumberOfWords-1]=lMessageLength>>>29;return lWordArray}function WordToHex(lValue){var WordToHexValue=
"",WordToHexValue_temp="",lByte,lCount;for(lCount=0;lCount<=3;lCount++){lByte=lValue>>>lCount*8&255;WordToHexValue_temp="0"+lByte.toString(16);WordToHexValue=WordToHexValue+WordToHexValue_temp.substr(WordToHexValue_temp.length-2,2)}return WordToHexValue}function Utf8Encode(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128)utftext+=String.fromCharCode(c);else if(c>127&&c<2048){utftext+=String.fromCharCode(c>>6|192);utftext+=
String.fromCharCode(c&63|128)}else{utftext+=String.fromCharCode(c>>12|224);utftext+=String.fromCharCode(c>>6&63|128);utftext+=String.fromCharCode(c&63|128)}}return utftext}var x=Array();var k,AA,BB,CC,DD,a,b,c,d;var S11=7,S12=12,S13=17,S14=22;var S21=5,S22=9,S23=14,S24=20;var S31=4,S32=11,S33=16,S34=23;var S41=6,S42=10,S43=15,S44=21;string=Utf8Encode(string);x=ConvertToWordArray(string);a=1732584193;b=4023233417;c=2562383102;d=271733878;for(k=0;k<x.length;k+=16){AA=a;BB=b;CC=c;DD=d;a=FF(a,b,c,d,x[k+
0],S11,3614090360);d=FF(d,a,b,c,x[k+1],S12,3905402710);c=FF(c,d,a,b,x[k+2],S13,606105819);b=FF(b,c,d,a,x[k+3],S14,3250441966);a=FF(a,b,c,d,x[k+4],S11,4118548399);d=FF(d,a,b,c,x[k+5],S12,1200080426);c=FF(c,d,a,b,x[k+6],S13,2821735955);b=FF(b,c,d,a,x[k+7],S14,4249261313);a=FF(a,b,c,d,x[k+8],S11,1770035416);d=FF(d,a,b,c,x[k+9],S12,2336552879);c=FF(c,d,a,b,x[k+10],S13,4294925233);b=FF(b,c,d,a,x[k+11],S14,2304563134);a=FF(a,b,c,d,x[k+12],S11,1804603682);d=FF(d,a,b,c,x[k+13],S12,4254626195);c=FF(c,d,a,
b,x[k+14],S13,2792965006);b=FF(b,c,d,a,x[k+15],S14,1236535329);a=GG(a,b,c,d,x[k+1],S21,4129170786);d=GG(d,a,b,c,x[k+6],S22,3225465664);c=GG(c,d,a,b,x[k+11],S23,643717713);b=GG(b,c,d,a,x[k+0],S24,3921069994);a=GG(a,b,c,d,x[k+5],S21,3593408605);d=GG(d,a,b,c,x[k+10],S22,38016083);c=GG(c,d,a,b,x[k+15],S23,3634488961);b=GG(b,c,d,a,x[k+4],S24,3889429448);a=GG(a,b,c,d,x[k+9],S21,568446438);d=GG(d,a,b,c,x[k+14],S22,3275163606);c=GG(c,d,a,b,x[k+3],S23,4107603335);b=GG(b,c,d,a,x[k+8],S24,1163531501);a=GG(a,
b,c,d,x[k+13],S21,2850285829);d=GG(d,a,b,c,x[k+2],S22,4243563512);c=GG(c,d,a,b,x[k+7],S23,1735328473);b=GG(b,c,d,a,x[k+12],S24,2368359562);a=HH(a,b,c,d,x[k+5],S31,4294588738);d=HH(d,a,b,c,x[k+8],S32,2272392833);c=HH(c,d,a,b,x[k+11],S33,1839030562);b=HH(b,c,d,a,x[k+14],S34,4259657740);a=HH(a,b,c,d,x[k+1],S31,2763975236);d=HH(d,a,b,c,x[k+4],S32,1272893353);c=HH(c,d,a,b,x[k+7],S33,4139469664);b=HH(b,c,d,a,x[k+10],S34,3200236656);a=HH(a,b,c,d,x[k+13],S31,681279174);d=HH(d,a,b,c,x[k+0],S32,3936430074);
c=HH(c,d,a,b,x[k+3],S33,3572445317);b=HH(b,c,d,a,x[k+6],S34,76029189);a=HH(a,b,c,d,x[k+9],S31,3654602809);d=HH(d,a,b,c,x[k+12],S32,3873151461);c=HH(c,d,a,b,x[k+15],S33,530742520);b=HH(b,c,d,a,x[k+2],S34,3299628645);a=II(a,b,c,d,x[k+0],S41,4096336452);d=II(d,a,b,c,x[k+7],S42,1126891415);c=II(c,d,a,b,x[k+14],S43,2878612391);b=II(b,c,d,a,x[k+5],S44,4237533241);a=II(a,b,c,d,x[k+12],S41,1700485571);d=II(d,a,b,c,x[k+3],S42,2399980690);c=II(c,d,a,b,x[k+10],S43,4293915773);b=II(b,c,d,a,x[k+1],S44,2240044497);
a=II(a,b,c,d,x[k+8],S41,1873313359);d=II(d,a,b,c,x[k+15],S42,4264355552);c=II(c,d,a,b,x[k+6],S43,2734768916);b=II(b,c,d,a,x[k+13],S44,1309151649);a=II(a,b,c,d,x[k+4],S41,4149444226);d=II(d,a,b,c,x[k+11],S42,3174756917);c=II(c,d,a,b,x[k+2],S43,718787259);b=II(b,c,d,a,x[k+9],S44,3951481745);a=AddUnsigned(a,AA);b=AddUnsigned(b,BB);c=AddUnsigned(c,CC);d=AddUnsigned(d,DD)}var temp=WordToHex(a)+WordToHex(b)+WordToHex(c)+WordToHex(d);return temp.toLowerCase()};var uniqid=function(prefix,more_entropy){if(typeof prefix==
"undefined")prefix="";var retId;var formatSeed=function(seed,reqWidth){seed=parseInt(seed,10).toString(16);if(reqWidth<seed.length)return seed.slice(seed.length-reqWidth);if(reqWidth>seed.length)return Array(1+(reqWidth-seed.length)).join("0")+seed;return seed};if(!this.php_js)this.php_js={};if(!this.php_js.uniqidSeed)this.php_js.uniqidSeed=Math.floor(Math.random()*123456789);this.php_js.uniqidSeed++;retId=prefix;retId+=formatSeed(parseInt((new Date).getTime()/1E3,10),8);retId+=formatSeed(this.php_js.uniqidSeed,
5);if(more_entropy)retId+=(Math.random()*10).toFixed(8).toString();return retId};return{service_id:null,portion:null,page:null,getUid:function(){var c_name="_mod_cnt";var getCookie=function(refresh){var c_value=document.cookie;var uid;var c_start=c_value.indexOf(" "+c_name+"=");if(c_start==-1)c_start=c_value.indexOf(c_name+"=");if(c_start==-1)uid=false;else{c_start=c_value.indexOf("=",c_start)+1;var c_end=c_value.indexOf(";",c_start);if(c_end==-1)c_end=c_value.length;c_value=unescape(c_value.substring(c_start,
c_end));var c_value_array=c_value.split("|");if(MD5(c_value_array[0]+c_value_array[2])==c_value_array[1]){uid=c_value_array[0];if(refresh)refreshCookie(uid);return uid}else uid=false}return uid};var refreshCookie=function(uid){var exdate=new Date;exdate.setDate(exdate.getDate()+730);if(!uid)return false;var c_value=uid+"|"+MD5(uid+__p_r_ct)+"|"+__p_r_ct+"; expires="+exdate.toUTCString();document.cookie=c_name+"="+c_value+";domain="+getDomain()+";path=/"};var setCookie=function(){var exdate=new Date;
exdate.setDate(exdate.getDate()+730);uid=MD5(uniqid(Math.floor(Math.random()*Number.MAX_VALUE),1));var c_value=uid+"|"+MD5(uid+__p_r_ct)+"|"+__p_r_ct+"; expires="+exdate.toUTCString();document.cookie=c_name+"="+c_value+";domain=."+getDomain()+";path=/";return getCookie(false)};var getDomain=function(){var i,h,weird_cookie="_mod_cnt_ctest=cookie",hostname=document.location.hostname.toLowerCase().split(".");for(i=hostname.length-1;i>=0;i--){h=hostname.slice(i).join(".");document.cookie=weird_cookie+
";domain=."+h+";";if(document.cookie.indexOf(weird_cookie)>-1){document.cookie=weird_cookie.split("=")[0]+"=;domain=."+h+";expires=Thu, 01 Jan 1970 00:00:01 GMT;";return h}}};if(!__p_n.cookieEnabled)return"";var uid=getCookie(true);if(!uid)uid=setCookie();if(!uid)return"";else return uid},run:function(){__p_r_ct=__p_da.getTime();if(typeof is_teljari_potency=="object"&&(typeof is_teljari_potency.service_id=="number"||typeof is_teljari_potency.service_id=="string"))this.service_id=is_teljari_potency.service_id;
else if(typeof service_id=="number"||typeof service_id=="string")this.service_id=service_id;else if(typeof owner=="number"||typeof owner=="string")this.service_id=owner;else if(typeof eigandi=="number"||typeof eigandi=="string")this.service_id=eigandi;else return false;if(typeof is_teljari_potency=="object"&&typeof is_teljari_potency.page=="string")this.page=is_teljari_potency.page;else if(typeof page=="string")this.page=page;else this.page=__p_r_t;if(typeof is_teljari_potency=="object"&&(typeof is_teljari_potency.portion==
"number"||typeof is_teljari_potency.portion=="string"))this.portion=is_teljari_potency.portion;else if(typeof portion=="string")this.portion=portion;else this.portion=0;__p_r_j=javascriptVersion();__p_r_u=__p_pi(__p_da.getTime()/1E3);__p_b_o=__p_io(__p_n_ua,"Opera")>=0;__p_b_ie=!__p_b_o&&__p_io(__p_n_av,"MSIE");__p_b_ie5=__p_io(__p_n_ua,"MSIE 5")>-1||__p_io(__p_n_ua,"MSIE 6");__p_b_ns=__p_n_an=="Netscape"?1:0;__p_b_ns6=__p_b_ns&&__p_pi(__p_n_av)>4;__p_b_mac=__p_io(__p_n_ua,"Mac")>-1;__p_x_o="Opera";
__p_b_v=Math.round(__p_pf(__p_n_av)*100);__p_l_pr=__p_io(__p_l.protocol.toLowerCase(),"https")>-1?"https":"http";__p_r_uid=this.getUid();__p_r_chsum=MD5(__p_r_uid+__p_r_u);if(__p_io(__p_n_av,__p_x_o)>-1||__p_io(__p_n_ua,__p_x_o)>-1)__p_b_ra=__p_x_o;try{__p_r_r=__p_e(top.document.referrer)+""}catch(e){__p_r_r=__p_e(document.referrer)+""}__p_rs=__p_pi(__p_io(__p_r_r.toLowerCase(),__p_l.hostname.toLowerCase()));if(__p_rs>=0&&__p_rs<11)__p_r_r="int";if(__p_r_r.length>=252)__p_r_r=__p_ss(__p_r_r,252)+
"...";if(__p_w.screen){__p_r_w=__p_s.width;__p_r_h=__p_s.height;__p_r_c=__p_b_ie?__p_s.colorDepth:__p_s.pixelDepth;if(__p_r_c=="undefined")__p_r_c=""}var isIE=navigator.appVersion.indexOf("MSIE")!=-1?true:false;var isWin=navigator.appVersion.toLowerCase().indexOf("win")!=-1?true:false;var isOpera=navigator.userAgent.indexOf("Opera")!=-1?true:false;if(navigator.plugins!=null&&navigator.plugins.length>0){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){var swVer2=navigator.plugins["Shockwave Flash 2.0"]?
" 2.0":"";var flashDescription=navigator.plugins["Shockwave Flash"+swVer2].description;var descArray=flashDescription.split(" ");var tempArrayMajor=descArray[2].split(".");var versionMajor=tempArrayMajor[0];var versionMinor=tempArrayMajor[1];var versionRevision=descArray[3];if(versionRevision=="")versionRevision=descArray[4];if(versionRevision[0]=="d")versionRevision=versionRevision.substring(1);else if(versionRevision[0]=="r"){versionRevision=versionRevision.substring(1);if(versionRevision.indexOf("d")>
0)versionRevision=versionRevision.substring(0,versionRevision.indexOf("d"))}var flashVer=versionMajor+"."+versionMinor+"."+versionRevision}}else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.6")!=-1)flashVer=4;else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.5")!=-1)flashVer=3;else if(navigator.userAgent.toLowerCase().indexOf("webtv")!=-1)flashVer=2;else if(isIE&&isWin&&!isOpera)flashVer=ControlVersion();if(!flashVer||flashVer==-1)__p_r_f=1;else{__p_r_f=2;__p_r_v=flashVer.replace(/WIN /,
"").replace(/,/g,".")}__p_r_sl=getSilverlightVersion();if(__p_b_v>3){if(__p_b_ie)__p_r_l=__p_n.userLanguage;if(__p_b_ns)__p_r_l=__p_n.language}if(!__p_b_mac&&__p_b_ie5&&__p_d.body&&__p_d.body.addBehavior){__p_d.body.addBehavior("#default#homePage");__p_r_s=__p_d.body.isHomePage(__p_l.href)?"1":"0";__p_d.body.addBehavior("#default#clientCaps");__p_r_k=__p_d.body.connectionType}__p_ccss();__p_counthost_http="potency-cnt.teljari.is";__p_counthost_https="secure.teljari.is";if(__p_l_pr=="https")__p_counthost=
__p_counthost_https;else __p_counthost=__p_counthost_http;var W3CDOM=document.createElement&&document.getElementsByTagName&&document.appendChild;if(!W3CDOM)document.write('<img id="__p_img" src="'+__p_l_pr+"://"+__p_counthost+"/potency/potency.php?o="+this.service_id+";p="+this.page+";i="+this.portion+__p_ms("cv","w","h","c","j","r","u","z","s","l","v","e","sl","uid","chsum")+'" alt="" border="0" />');else{var potency_image=document.createElement("img");potency_image.alt="";potency_image.width=1;
potency_image.height=1;potency_image.src=__p_l_pr+"://"+__p_counthost+"/potency/potency.php?o="+this.service_id+";p="+this.page+";i="+this.portion+__p_ms("cv","w","h","c","j","r","u","z","s","l","v","e","sl","uid","chsum");var imgFunction=function(){var body=document.getElementsByTagName("body")[0];body.appendChild(potency_image)};if(window.addEventListener)window.addEventListener("load",imgFunction,false);else if(window.attachEvent)window.attachEvent("onload",imgFunction)}}}};teljari_is().run();
